# Generated by Django 5.1.4 on 2025-01-21 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='user/photos/')),
                ('photo_type', models.CharField(choices=[('P', 'Profile'), ('L', 'Living Spcae')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user/profile_pics/')),
                ('smoking_allowed', models.BooleanField()),
                ('pets_allowed', models.BooleanField()),
                ('early_riser', models.BooleanField()),
                ('vegeterian', models.BooleanField()),
                ('gender_same_prefer', models.BooleanField()),
                ('introvert', models.BooleanField()),
                ('min_budget', models.PositiveIntegerField()),
                ('max_budget', models.PositiveIntegerField()),
                ('is_looking', models.BooleanField()),
                ('drinking_allowed', models.BooleanField(default=False)),
                ('has_room', models.BooleanField(default=False)),
                ('room_type', models.CharField(blank=True, choices=[('S', 'Shared'), ('P', 'Private')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
