# Generated by Django 5.1.4 on 2024-12-29 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user/profile_pics/')),
                ('smoking_allowed', models.BooleanField()),
                ('pets_allowed', models.BooleanField()),
                ('early_riser', models.BooleanField()),
                ('vegeterian', models.BooleanField()),
                ('gender_same_prefer', models.BooleanField()),
                ('introvert', models.BooleanField()),
                ('min_budget', models.PositiveIntegerField()),
                ('max_budget', models.PositiveIntegerField()),
                ('is_looking', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
