# Generated by Django 5.1.4 on 2025-01-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_type',
            field=models.CharField(blank=True, choices=[('S', 'Shared'), ('P', 'Private')], max_length=1, null=True),
        ),
    ]
