# Generated by Django 5.1.4 on 2025-01-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='drinking_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
